global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "example-nodejs-app"
    static_configs:
      - targets: ["example-nodejs-app:8080"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["172.17.0.1:9100"]
